# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Tinypng Compress

on:
  watch:
    types: [started]

jobs:
  tinypng:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get upgrade
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tinify
    - name: start compression
      run: |
        cd /home/runner/work/picdev/picdev
        rm -f imgs/web-ani/*
        python tiny.py
    - name: Delect Rawfile
      run: |
        cd /home/runner/work/picdev/picdev
        rm -rf imgs/ani
        rm -rf img
    - name: Push to Repo
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Tinypng compress
